### PR TITLE
Missing AMD Module name

### PR DESCRIPTION
**Pull request by alexandrahrastnik**
This source file was missing an AMD module name. Other parts of the DataTables source collection (e.g. datatables.net-fixedheader) require module 'datatables.net'.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for the PR, but DataTables is intentionally an unnamed module. The AMD specification [says that](http://requirejs.org/docs/whyamd.html#namedmodules) it is more portable for modules not to be named.

**Comment by alexandrahrastnik** [comment]
So, how am I supposed to use datatables.net along with datatables.net-fixedheader? Using both components in one project leads to an AMD error "undefined missing datatables.net" in datatables.net-fixedheader
@DataTables

**Comment by DataTables** [comment]
Have you defined `datatables.net` in your loader configuration?

You are right that `datatables.net` basically _should_ be the name used - but I ran into a lot of people not wanting it to be a named module back when it was.

**Comment by alexandrahrastnik** [comment]
@DataTables The basic loader attempt is to name the module after the file containing the source. That's why a default loader uses "jquery.dataTables" as module name instead of "datatables.net" - would be more comfortable to use if the file name was acutally the same as the module name to use furtherwards.
But it's how it is - thanks for support.

**Pull request closed without merging**
